### ISSUE TITLE
Not working with python3

### ISSUE THREAD

**Issue by hanxue** [cykl/infoqscraper#17]
When I run on python3, including the tests, I get a lot of errors - https://travis-ci.org/hanxue/infoqscraper/jobs/14867284

Pardon my limited Python knowledge - is infoqscraper written for Python 2.x and no foreseeable plans to support Python 3.x?

**Comment by FranciscoE-Hudl** [comment]
Bump

**Comment by cykl** [comment]
Hi Francisco,

IIRC I added Python 3 support several years ago but forgot to close this issue. Are you facing an issue ?

**Comment by FranciscoE-Hudl** [comment]
I tried using it today with python 2, but had to fall back to python 2.

OSX default instalation of Anaconda, and brew's version of Python 2.7.

I may be able to fetch the bug tomorrow.

**Comment by cykl** [comment]
I am closing this one. 

You are welcome to open a new ticket if you face any issue with python 3 or OS X.
