### ISSUE TITLE
Only first slide visible.

### ISSUE THREAD

**Issue by ashnur** [cykl/infoqscraper#24]
I am on Arch Linux(updated), followed the wiki when installing infoqscraper.

Used the command `infoqscraper presentation download The-Design-of-Datomic`

Only the first slide is visible, nothing else. The audio is fine.

**Comment by cykl** [comment]
I failed to reproduce the issue using a freshly updated system.

Can you confirm you are using the latest release ? (infoqscraper -V)
Which player are you using ?

**Comment by ashnur** [comment]
The version was the latest, just installed it.
I am not at my home box now, tried it at work too, and here it worked fine, as expected. When I will get home I test it again, and if it works — hopefully — I will close this issue.

**Comment by ashnur** [comment]
You were right, it was a player error, mpv plays the file correctly, sorry for the false report.
