### ISSUE TITLE
Proportional scale for overlay

### ISSUE THREAD

**Issue by zerkms** [cykl/infoqscraper#25]
How about switching to `scale=w=320:h=-1` instead of `scale=320x240` so that it was not distorted?

Then the filter config could be changed from

    [tmp1][speaker] overlay=shortest=1:x=main_w-320:y=main_h-240

to

    [tmp1][speaker] overlay=shortest=1:x=main_w-320:y=main_h-h

I patched the local installation and it works great.

**Comment by cykl** [comment]
Good idea. 

IIRC I had to fiddle quite a lot to support a broad range of ffmpeg versions (some of Debian stable, Ubuntu LTS, Centos comes with a really old version). Do you know since when the -1 syntax is supported ?

**Comment by zerkms** [comment]
I don't know but it's already used on the other line `"[1:v] setpts=PTS-STARTPTS, scale=w=1280-320:h=-1[slides];",` https://github.com/cykl/infoqscraper/blob/master/infoqscraper%2Fconvert.py#L203

**Comment by cykl** [comment]
Good catch. Do you want to submit a pull request or do you want me to write the patch ?

**Comment by zerkms** [comment]
Yep, prepared one.
