### ISSUE TITLE
Feature suggestion: demos

### ISSUE THREAD

**Issue by zerkms** [cykl/infoqscraper#27]
This suggestion is for `h264_overlay` mode specifically

How about adding demos fullscreen, when the presentation switches into the full screen player mode?

They store the `begin,end` positions as the pairs of numbers in the `demoTimings` variable.

The solution would be to create multiple slices of the presentation: slides&video, demo, slides&video, demo, etc followed by a concatenation operation.

What it would change:

* The runtime would require ~1x compressed video size extra to keep the intermediate videos and I believe the overall encoding time should not change.
* It's not obvious to me if videos would concatenate seamlessly or some sound distortion would appear, but I as a software user am ready to pay the price in favour of having the full screen demo, not a tiny thing in the corner.

It might be implemented as an additional switch to keep BC.

If you like the idea and would accept it - I might spent few evenings to implement it.

**Comment by cykl** [comment]
Hi Yvan,

It sounds like an useful feature to add.

Not sure how I would implement it myself, but let me know if you need any advice / feedback / early review.

**Comment by zerkms** [comment]
Yep, how I see the implementation:

1. Check if there are any `demoTimings`
2. If not - it would behave as it currently does
3. If it does - generate N video cuts for every slide+presenter and demo parts (here the parts will be already encoded)
4. concatenate those parts (https://trac.ffmpeg.org/wiki/Concatenate --- see "concat demuxer")

I'll try something today and I hope there will be something committed into my fork this week (and I will regret later for putting any estimations :-D )

**Comment by zerkms** [comment]
So intermediate results:

I tried 2 different approaches: the one from the comment above and the other (where I cut video without audio first, added slides and composed it all together with a single audio track added on top).

The latter failed miserably with de-synced audio (that's what I honestly expected but needed to confirm), and the former worked greatly.

In short the algorithm is almost as I described - so the parts are generated/encoded separately and then concatenated. For the concatenation to happen successfully all must have the same encoding parameters. What I have found is that when we combine video with slides - ffmpeg changes the fps from 29.97 (from the original infoq videos) to 25 (since the 2 video tracks have different fpses: slides are 1fps and video is 29.97 - it takes the default value that is 25). So for this problem to be resolved - the fps of the every resulted chunk created from presenter video+slides must be set explicitly to 29.97. Or more generally: before encoding process the fps for the original video must be determined and used everywhere else.

**Comment by zerkms** [comment]
Here I have implemented the algorithm from above: https://github.com/zerkms/infoqscraper/tree/demo-mode

The implementation is quick and dirty and requires polishing, but technically it does what I wanted it to.

**Comment by zerkms** [comment]
I've just pushed another commit https://github.com/zerkms/infoqscraper/commit/3fefdb7588867dffacf629799df41a5920ee5c36 with cleaning up.

As a test I downloaded few videos including http://www.infoq.com/presentations/netflix-failure-multiple-regions and sadly it has audio out of sync (minor but noticeable if you're carefully checking for it).

I will try to make investigation about it, but I'm 99% sure that the sliced-and-compressed videos are fine, but it's the concatenation operation that makes it out of sync.

**Comment by cykl** [comment]
Sorry for my late reply. 

It's both nice to hear that you are making progress and unfortunate that you have to fight with some ffmpeg wizardry. 

I quickly read the patch. Your approach looks clean & sensible. I'm currently too busy to be of any valuable help. I will try to play with your branch & give a look at the SO answer when things calm down.

BTW: Wouldn't it be useful to add the same feature to the other outputs ? I think it would better to watch the speaker or his screen rather than a most likely useless/stall slide. I'm not asking you to implement the feature if you don't need it, just want a confirmation the it would be useful (I haven't watched a presentation with a demo since years).

**Comment by zerkms** [comment]
>  I'm currently too busy to be of any valuable help. I will try to play with your branch & give a look at the SO answer when things calm down.

it's totally fine: I'm doing it to make my experience better, if it helps someone else - even better :-) At the moment I'm comfortable with the problem and will spend few more evenings diving into the synchronisation problem.

> Wouldn't it be useful to add the same feature to the other outputs ? I think it would better to watch the speaker or his screen rather than a most likely useless/stall slide. I'm not asking you to implement the feature if you don't need it, just want a confirmation the it would be useful (I haven't watched a presentation with a demo since years.

It would be indeed. I would suggest to add it after the code is stabilised and merged.

> I would be interested in a list of such presentations if you have one).

From what I've watched personally in the last few days:

* http://www.infoq.com/presentations/netflix-failure-multiple-regions
* http://www.infoq.com/presentations/template-spring-boot-nashorn

**Comment by zerkms** [comment]
So, I have spent some more time and produced another change https://github.com/zerkms/infoqscraper/commit/5bae547ab06f6470957c1512667f7d6785f02b7d

It fixes the async by the cost of having some sound played twice on the place where 2 videos overlap.

I'm not sure how to explain it better, but the last few dosens milliseconds of video and audio present in both slides- and demo-modes, which causes the same dosens of milliseconds on the place where 2 slices connect to repeat.

Personally I'm ready to accept it as a payment to have fullscreen demos since such sound artifact not a big deal for me (I don't expect much quality from watching videos on the phone in trains anyway).

It's likely I will not be able to make it any better since I'm seriously lacking knowledge of codecs and containers required to complete the task ideally.

I think it makes sense for you to check it and see how good/bad it is.

As an example I used http://www.infoq.com/presentations/netflix-failure-multiple-regions, which has 4 demo sessions hence very convenient to check this new mode.

**Comment by zerkms** [comment]
Good news, I have spent few more times with the ffmpeg documentation and google and found a way to combine/concat everything in a one pass, which produces seamless result with no async!

At the moment it only exists as the terribly long `complex_filter` and I'm going to code it this or tomorrow evening.

**Comment by zerkms** [comment]
Nope, there is async 😠

**Comment by zerkms** [comment]
Implemented in https://github.com/cykl/infoqscraper/pull/28
